- name: disable node js
  ansible.builtin.command: dnf module disable nodejs -y 

- name: enable node js
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install node js
  ansible.builtin.command: dnf install nodejs -y

- name: add user
  ansible.builtin.user:
    name: expense

- name: create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: create url
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: unzip the downloaded file
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: install dependencies
  community.general.npm:
    path: /app

- name: copy file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service